# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-21 16:41
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import s2m.core.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('content', models.TextField(default='')),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('is_in_trash', models.BooleanField(default=False)),
                ('last_modification_date', models.DateField(auto_now=True)),
                ('pdf', models.FileField(default='', upload_to='latex_files/')),
                ('title', models.CharField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='ElementaryFormula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('formula', models.TextField(validators=[s2m.core.utils.is_pickled_formula])),
                ('count', models.IntegerField(default=1)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elementary_formulae', to='interface.Document')),
            ],
        ),
        migrations.CreateModel(
            name='PendingFormulae',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=12, unique=True)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('formulae', models.TextField(validators=[s2m.core.utils.is_pickled_formula_list])),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_formulae', to='interface.Document')),
            ],
        ),
        migrations.CreateModel(
            name='S2MModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_model', models.TextField(default='{"backend": "tensorflow", "keras_version": "2.1.5", "class_name": "Sequential", "config": [{"class_name": "Dense", "config": {"bias_regularizer": null, "kernel_regularizer": null, "kernel_constraint": null, "name": "dense_1", "units": 32, "bias_constraint": null, "trainable": true, "activity_regularizer": null, "dtype": "float32", "activation": "relu", "kernel_initializer": {"class_name": "VarianceScaling", "config": {"scale": 1.0, "seed": null, "distribution": "uniform", "mode": "fan_avg"}}, "bias_initializer": {"class_name": "Zeros", "config": {}}, "batch_input_shape": [null, 9], "use_bias": true}}, {"class_name": "Dense", "config": {"bias_regularizer": null, "kernel_regularizer": null, "kernel_constraint": null, "units": 32, "bias_constraint": null, "trainable": true, "activity_regularizer": null, "name": "dense_2", "activation": "relu", "kernel_initializer": {"class_name": "VarianceScaling", "config": {"scale": 1.0, "seed": null, "distribution": "uniform", "mode": "fan_avg"}}, "bias_initializer": {"class_name": "Zeros", "config": {}}, "use_bias": true}}, {"class_name": "Dense", "config": {"bias_regularizer": null, "kernel_regularizer": null, "kernel_constraint": null, "units": 1, "bias_constraint": null, "trainable": true, "activity_regularizer": null, "name": "dense_3", "activation": "sigmoid", "kernel_initializer": {"class_name": "VarianceScaling", "config": {"scale": 1.0, "seed": null, "distribution": "uniform", "mode": "fan_avg"}}, "bias_initializer": {"class_name": "Zeros", "config": {}}, "use_bias": true}}]}')),
            ],
        ),
        migrations.CreateModel(
            name='SavedFormula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('formula', models.TextField(validators=[s2m.core.utils.is_pickled_formula])),
                ('count', models.IntegerField(default=1)),
                ('chosen', models.BooleanField(default=False)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_formulae', to='interface.Document')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='training_data')),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('converted_to_wav', models.BooleanField(default=False)),
                ('text', models.TextField()),
                ('used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('s2m_model', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='interface.S2MModel')),
            ],
            options={
                'verbose_name': 'user',
                'abstract': False,
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='trainingsample',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.Utilisateur'),
        ),
        migrations.AddField(
            model_name='document',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.Utilisateur'),
        ),
        migrations.AddField(
            model_name='document',
            name='s2m_model',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='interface.S2MModel'),
        ),
    ]
