# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-31 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import interface.models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementaryFormula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('formula', models.CharField(max_length=255, validators=[interface.models.ElementaryFormula.validate_formula])),
                ('count', models.IntegerField(default=1)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elementary_formulae', to='interface.Document')),
            ],
        ),
        migrations.RemoveField(
            model_name='documentconstant',
            name='document',
        ),
        migrations.DeleteModel(
            name='GeneralConstant',
        ),
        migrations.RemoveField(
            model_name='userconstant',
            name='user',
        ),
        migrations.DeleteModel(
            name='DocumentConstant',
        ),
        migrations.DeleteModel(
            name='UserConstant',
        ),
    ]
