# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_in_trash',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
