# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-08 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0003_document_is_in_trash'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='latex',
            field=models.FileField(default='', upload_to='latex_files/'),
        ),
    ]
