# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-08 15:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0004_document_latex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='latex',
            new_name='pdf',
        ),
    ]
