# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-25 20:38
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0007_document_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='adress',
            field=models.TextField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='document',
            name='is_in_trash',
            field=models.BooleanField(default=False),
        ),
    ]
