# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-27 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0008_auto_20170925_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='adress',
            field=models.TextField(),
        ),
    ]
