# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-27 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0009_auto_20170927_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='adress',
            field=models.TextField(default=uuid.UUID('804cbf95-10e6-47ef-9de5-8b9ff0cfc23b')),
        ),
    ]
