# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-08 01:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0010_auto_20170927_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='training_data/')),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('converted_to_wav', models.BooleanField(default=False)),
                ('text', models.TextField()),
                ('used', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.Utilisateur')),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='adress',
            field=models.TextField(default=uuid.UUID('c8154a28-e860-426e-b271-b7bac5e73876')),
        ),
    ]
