# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-08 01:38
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0011_auto_20171008_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='adress',
            field=models.TextField(default=uuid.UUID('675160bc-e71a-4f09-8add-fb15d0549f87')),
        ),
        migrations.AlterField(
            model_name='trainingsample',
            name='audio',
            field=models.FileField(upload_to='training_data'),
        ),
    ]
