# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-08 01:40
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0012_auto_20171008_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='adress',
            field=models.TextField(default=uuid.UUID('750c34ae-891a-4448-9f0b-f95ea4d7cbbe')),
        ),
    ]
