# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-09 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0013_auto_20171008_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='adress',
            field=models.TextField(default=uuid.UUID('7463f738-ce37-4aa7-8273-5bfaedef82d2')),
        ),
    ]
