# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-09 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0014_auto_20171009_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='adress',
        ),
        migrations.AddField(
            model_name='document',
            name='address',
            field=models.TextField(default=uuid.UUID('4f0ba474-2da1-4a4d-b3bb-380eb271a6ee')),
        ),
    ]
