# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-09 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0015_auto_20171009_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='address',
            field=models.TextField(),
        ),
    ]
