# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-09 13:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0016_auto_20171009_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingsample',
            old_name='converted_to_wav',
            new_name='converted_to_wavv',
        ),
    ]
